###
DELETE http://localhost:8080/api/v1/books/100
Accept: application/json

###
PUT http://localhost:8080/api/v1/books
Content-Type: application/x-www-form-urlencoded

id=10&title="DEMO"

###
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "id":111,
  "title": "java"
}



###
POST http://localhost:8080/api/v1/books/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="simple.jpg"

< ./simple.jpg
--WebAppBoundary--

###
GET http://localhost:8080/api/v1/books/111
Accept: application/json

###
GET http://localhost:8080/api/v1/books/all
Accept: application/json

###
